export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const GET_POSTS_BY_CATEGORIES = 'GET_POSTS_BY_CATEGORIES';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const ADD_POST = 'ADD_POST';
export const GET_POST = 'GET_POST';
export const VOTE_POST = 'VOTE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_COMMENT = 'GET_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SORT_BY_NEWEST_POST = 'SORT_BY_NEWEST_POST';
export const SORT_BY_OLDEST_POST = 'SORT_BY_OLDEST_POST';
export const SORT_BY_HIGHEST_VOTE_SCORE = 'SORT_BY_HIGHEST_VOTE_SCORE';
export const SORT_BY_LOWEST_VOTE_SCORE = 'SORT_BY_LOWEST_VOTE_SCORE';